from app.models.schema import IntakeState
from typing import Dict, Any

class DocumentGenerator:
    """
    Generates a markdown draft of the Personal Wishes Document from the IntakeState.
    """
    def generate(self, state: IntakeState) -> str:
        # Legal disclaimer is mandatory
        doc = []
        doc.append("# DRAFT - PERSONAL WISHES DOCUMENT")
        doc.append("\n> **FICTIONAL DRAFT - NOT LEGAL ADVICE**")
        doc.append("> This document is generated for demonstration purposes only and does not constitute a valid legal document.")
        
        doc.append("\n## 1. Testator Details")
        name = state.full_name if state.full_name else "[UNCONFIRMED NAME]"
        address = state.home_address if state.home_address else "[UNCONFIRMED ADDRESS]"
        doc.append(f"- **Full Name**: {name}")
        doc.append(f"- **Address**: {address}")
        
        doc.append("\n## 2. Estate Scope")
        assets = "Worldwide Assets" if state.covers_worldwide_assets else "Domestic Assets Only"
        if state.covers_worldwide_assets is None:
            assets = "[UNCONFIRMED SCOPE]"
        doc.append(f"- **Coverage**: This document covers {assets}.")
        
        doc.append("\n## 3. Family")
        if state.has_children is None:
            doc.append("- **Children**: [UNCONFIRMED]")
        elif not state.has_children:
            doc.append("- **Children**: None")
        else:
            children_list = ", ".join(state.children_names) if state.children_names else "[UNCONFIRMED NAMES]"
            doc.append(f"- **Children**: {children_list}")
            
        doc.append("\n## 4. Executor")
        exec_name = state.executor.name if state.executor.name else "[UNCONFIRMED EXECUTOR NAME]"
        exec_rel = state.executor.relationship if state.executor.relationship else "[UNCONFIRMED RELATIONSHIP]"
        doc.append(f"- **Primary Name**: {exec_name}")
        doc.append(f"- **Primary Relationship**: {exec_rel}")
        
        if state.backup_executor.name and state.backup_executor.name.lower() == "none":
            doc.append("- **Backup Executor**: None")
        else:
            b_exec_name = state.backup_executor.name if state.backup_executor.name else "[UNCONFIRMED BACKUP NAME]"
            b_exec_rel = state.backup_executor.relationship if state.backup_executor.relationship else "[UNCONFIRMED BACKUP RELATIONSHIP]"
            doc.append(f"- **Backup Name**: {b_exec_name}")
            doc.append(f"- **Backup Relationship**: {b_exec_rel}")
        
        doc.append("\n## 5. Specific Gifts")
        gifts = state.specific_gifts if state.specific_gifts else "None specified."
        doc.append(f"{gifts}")
        
        doc.append("\n## 6. Additional Wishes")
        wishes = state.additional_wishes if state.additional_wishes else "None specified."
        doc.append(f"{wishes}")
        
        doc.append("\n---\n*Generated by Document Intake Assistant*")
        
        return "\n".join(doc)
